language: ruby
sudo: false
dist: trusty

rvm: 2.5.3

stages:
  - lint
  - test

jobs:
  include:
    allow_failures:
      - stage: "lint"
    - stage: lint
      before_install:
        - gem install rubocop
        script:
          - rubocop # https://rubocop.readthedocs.io/en/latest/basic_usage/
    - stage: test
      before_install:
        - bundler install
      script:
        - bundle exec ruby test/*.rb