language: ruby
sudo: false
dist: trusty

rvm: 2.5.3

stages:
  - build
  - identities
  - sparse_tests

jobs:
  include:
    - stage: build
      script:
        - ./scripts/setup.sh
    - stage: identities
      script:
        - ruby test/matrix_identities_test.rb
    - stage: sparse_tests
      script:
        - ruby test/sparse_*.rb