language: ruby
sudo: false
dist: trusty

rvm: 2.5.3

stages:
  - test

jobs:
  include:
    - stage: test
      before_install:
        - ./scripts/setup.sh
      script:
        - bundle exec ruby test/*.rb