language: ruby
sudo: false
dist: trusty

rvm: 2.5.3

stages:
  - identities
  - sparse_tests

before_install:
  - ./scripts/setup.sh

jobs:
  include:
    - stage: identities
      script:
        - ruby test/matrix_identities_test.rb
    - stage: sparse_tests
      script:
        - ruby test/sparse_*.rb