language: ruby
sudo: false
dist: trusty

rvm: 2.5.3

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      script:
        - ./scripts/setup.sh
    - stage: test
      script:
        - find test -name '*_test.rb' | xargs -n1 -I{} ruby -Itest {}